version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: examples/Dockerfile
    command: uvicorn examples.app1:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=app1
    depends_on:
      - otel-collector
    networks:
      - observability

  app2:
    build:
      context: .
      dockerfile: examples/Dockerfile
    command: uvicorn examples.app2:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=app2
    depends_on:
      - otel-collector
    networks:
      - observability

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./configs/otel-collector.yml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - observability

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    user: root
    volumes:
      - ./configs/tempo.yml:/etc/tempo/tempo.yml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"
      - "9411:9411"
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    user: root
    ports:
      - "3100:3100"
      - "3111:3111"
    volumes:
      - ./configs/loki.yml:/etc/loki/local-config.yml
      - loki_data:/loki
    networks:
      - observability

networks:
  observability:
    driver: bridge

volumes:
  tempo_data:
  loki_data: 