global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app1'
    static_configs:
      - targets: ['app1:8000']
    metrics_path: '/metrics'
    
  - job_name: 'app2'
    static_configs:
      - targets: ['app2:8000']
    metrics_path: '/metrics'
    
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889'] 