name: Test

on:
  push:
    branches: [ main, feat-init-lib ]
  pull_request:
    branches: [ main, feat-init-lib ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        pytest tests/ -v
    
    - name: Run linting
      run: |
        flake8 src/fastapi_observability
        mypy src/fastapi_observability
        isort --check-only src/fastapi_observability
        black --check src/fastapi_observability 